### ISSUE TITLE
Password filed transparent

### ISSUE THREAD

**Issue by cristovao-trevisan** [Justin-Credible/cordova-plugin-password-dialog#1]
As the title says, nothing shows in the password field (running on Android 4.4.3).
Screenshot:
![screenshot_2016-12-18-22-55-27](https://cloud.githubusercontent.com/assets/4981855/21298269/baa65616-c575-11e6-8a7f-0052fa5b20e1.png)

**Comment by Justin-Credible** [comment]
Thanks for reporting this issue, sorry I didn't see it sooner!

The proposed change would fix the issue for themes with light backgrounds, but would cause problems with dark themes (Galaxy S3).

![screen](https://user-images.githubusercontent.com/1243565/31917838-8b639f80-b80e-11e7-8712-8c6f7e8699d0.png)

**Comment by cristovao-trevisan** [comment]
Close due to inactivity
