### ISSUE TITLE
How do we access the input values?

### ISSUE THREAD

**Issue by nickstucko** [Justin-Credible/cordova-plugin-password-dialog#5]
Hey there - awesome plugin!

How can we access the input values after the user submits - so that we are able to evaluate the entered credentials?

Thanks again!

**Comment by Justin-Credible** [comment]
You should be able to access the user's input data  from within the callback. Examples for each of the dialog types are provided in the readme.

For example:

```
var options = {
    title: "Change Password",
    message: "Please change your password.",
    minLength: 8
};

PasswordDialogPlugin.showChangePassword(options,
    function(result) {
        if (result.cancel) {
            console.log("User cancelled the change password dialog.");
        }
        else {
            console.log("User completed the change password dialog.", result.currentPassword, result.newPassword);
        }
    },
    function(err) {
        console.log("Change password dialog error.", err);
    });
```

**Comment by nickstucko** [comment]
@Justin-Credible I actually just saw that - so for the username, is it just result.userName?

Thank you again!

**Comment by Justin-Credible** [comment]
Yep, you can see the types here:

https://github.com/Justin-Credible/cordova-plugin-password-dialog/blob/master/typings/cordova-plugin-password-dialog.d.ts#L93

**Comment by nickstucko** [comment]
Thank you again, have a great holiday!
